### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by sputnick-dev** [pinae/DeepL-Console-Translator#7]
```
$ pip2 list | grep -E 'wheel|requests|pip'
pip                      10.0.0          
requests                 2.18.4          
wheel                    0.31.0
```

```
$ python3 translate.py -s FR "what's the fuck?"
Traceback (most recent call last):
  File "translate.py", line 62, in <module>
    main()
  File "translate.py", line 49, in main
    translations = req.json()['result']['translations']
KeyError: 'result'
```

With archlinux x86_64

**Comment by 5t4rdu5t** [comment]
Workaround https://github.com/uinput/deeplator
